from tkinter import *
from tkinter.messagebox import *
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
img=PhotoImage(file=".\\Bus_for_project.png")
Label(root,image=img).grid(row=0,column=1,padx=w//3,columnspan=15)
Label(root,text='Online Bus Booking System',fg="red",bg="sky blue",font=('Times',24)).grid(row=1,column=2,pady=25,padx=25,columnspan=10)
Label(root,text='Add Bus Details',font='Arial 10 bold',bg='grey97',fg='dark green').grid(row=3,column=3,pady=20,columnspan=6)
Label(root,text='Bus id',font='Arial 10 bold').grid(row=4,column=0)
Entry(root,font='Arial 10 bold').grid(row=4,column=1)
Label(root,text='Bus Type',font='Arial 10 bold').grid(row=4,column=2)
bus_type=StringVar()
bus_type.set('Bus Type')
opt=['AC 2X2','AC 3X2','Non AC 2X2','Non AC 3X2','AC-Sleeper 2X1','Non-AC-Sleeper 2X1']
d_menu=OptionMenu(root,bus_type,*opt).grid(row=4,column=3)
Label(root,text='Capacity',font=('Arial', 10 ,'bold')).grid(row=4,column=4)
Entry(root).grid(row=4,column=5)
Label(root,text='Fare',font=('Arial', 10 ,'bold')).grid(row=4,column=6)
Entry(root).grid(row=4,column=7)
Label(root,text='Operator ID',font=('Arial', 10,'bold')).grid(row=4,column=8)
Entry(root).grid(row=4,column=9)
Label(root,text='Route id',font=('Arial', 10 ,'bold')).grid(row=4,column=10)
Entry(root).grid(row=4,column=11,pady=39)
Button(root,text='Add Bus',font=('Arial', 10,'bold'),bg='light green',fg='dark green').grid(row=5,column=4)
Button(root,text='Edit Bus',font=('Arial', 10 ,'bold'),bg='light green',fg='dark green').grid(row=5,column=5)
immg=PhotoImage(file=".\\home.png")
Button(root,image=immg).grid(row=5,column=6)
showinfo('Bus Entry','Bus record added')
root.mainloop()
