from tkinter import*
root=Tk()
h,w=root.winfo_screenheight(),root.winfo_screenwidth()
root.geometry('%dx%d+0+0'%(w,h))
img=PhotoImage(file=".\\Bus_for_project.png")
Label(root,image=img).grid(row=0,column=1,padx=w//3,columnspan=15)
Label(root,text='Online Bus Booking System',fg="red",bg="sky blue",font=('Times',24)).grid(row=1,column=1,pady=25,padx=12,columnspan=10)
Label(root,text='Add Bus Route Details',font='Arial 14 bold',bg='grey97',fg='dark green').grid(row=3,column=3,pady=20,columnspan=4)
Label(root,text='Route id',font='Arial 14 bold').grid(row=4,column=0)
Entry(root,font='Arial 14 bold').grid(row=4,column=1)
Label(root,text='Station Name',font='Arial 14 bold').grid(row=4,column=2)
Entry(root,font='Arial 14 bold').grid(row=4,column=3)
Label(root,text='Station id',font='Arial 14 bold').grid(row=4,column=4)
Entry(root,font='Arial 14 bold').grid(row=4,column=5)
Button(root,text='Add Route',font='Arial 14 bold',bg='light green',fg='dark green').grid(row=4,column=7,padx=15)
Button(root,text='Delete Route',font='Arial 14 bold',bg='light green',fg='red').grid(row=4,column=8,pady=20)
immg=PhotoImage(file=".\\home.png")
Button(root,image=immg).grid(row=4,column=6)
root.mainloop()
